config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :names
  root 'welcome#index'
  resources :posts
  resources :pages
  get '/playground', to: 'playground#index'
  get '/readme', to: 'readme#index'
  # The "to:" key specifies which controllers action method the request should be sent to.
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/name.rb
class Name < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/playground.rb
class Playground < ApplicationController
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/models/welcome.rb
class Playground < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :set_name, only: [:show, :edit, :update, :destroy]

  # GET /names
  # GET /names.json
  def index
    @names = Name.all
  end

  # GET /names/1
  # GET /names/1.json
  def show
  end

  # GET /names/new
  def new
    @name = Name.new
  end

  # GET /names/1/edit
  def edit
  end

  # POST /names
  # POST /names.json
  def create
    @name = Name.new(name_params)

    respond_to do |format|
      if @name.save
        format.html { redirect_to @name, notice: 'Name was successfully created.' }
        format.json { render :show, status: :created, location: @name }
      else
        format.html { render :new }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /names/1
  # PATCH/PUT /names/1.json
  def update
    respond_to do |format|
      if @name.update(name_params)
        format.html { redirect_to @name, notice: 'Name was successfully updated.' }
        format.json { render :show, status: :ok, location: @name }
      else
        format.html { render :edit }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1
  # DELETE /names/1.json
  def destroy
    @name.destroy
    respond_to do |format|
      format.html { redirect_to names_url, notice: 'Name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name
      @name = Name.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def name_params
      params.require(:name).permit(:content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    @page.save
    redirect_to @page
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    @page.update(page_params)
    redirect_to @page
  end

  def destroy
    @page = Page.destroy(params[:id])
    @page.destroy
    redirect_to '/pages'
  end

  private

    def page_params
      params.require(:page).permit(:title, :body, :slug)
    end
end

app/controllers/playground_controller.rb
class PlaygroundController < ApplicationController
  def index
    render template: 'playground/index.html.erb'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    render template: 'posts/index.html.erb', layout: 'application'
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/readme_controller.rb
class ReadmeController < ApplicationController

  def index
    render template: 'readme/index.html.erb', layout: 'application'
  end

  def show; end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Highlight root nav link
  def current_class?(test_path)
    return 'active' if request.path == test_path
  end
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/readme_helper.rb
module ReadmeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= yield(:title) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<header></header>
<body>

  <%= render 'shared/nav' %>
  <%= yield %>

</body>
</html>

app/views/names/_form.html.erb
<%= form_with(model: name, local: true) do |form| %>
  <% if name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
        <% name.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/names/edit.html.erb
<h1>Editing Name</h1>

<%= render 'form', name: @name %>

<%= link_to 'Show', @name %> |
<%= link_to 'Back', names_path %>

app/views/names/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', 'javascript:history.back()', class: 'link-to' %>

<h1>Names</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @names.each do |name| %>
      <tr>
        <td><%= name.content %></td>
        <td><%= link_to 'Show', name %></td>
        <td><%= link_to 'Edit', edit_name_path(name) %></td>
        <td><%= link_to 'Destroy', name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Name', new_name_path %>

app/views/names/new.html.erb
<h1>New Name</h1>

<%= render 'form', name: @name %>

<%= link_to 'Back', names_path %>

app/views/names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @name.content %>
</p>

<%= link_to 'Edit', edit_name_path(@name) %> |
<%= link_to 'Back', names_path %>

app/views/pages/_form.html.erb
<%= form_for(page) do |form| %>
  <h2><%= @page.title %></h2>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<%= content_for :title, "Edit %s Page" %[@page.title] %>
<h1>Edit Page:</h1>
<%= render 'form', page: @page %>
<%= link_to 'Back to All Pages', '/pages' %>

app/views/pages/index.html.erb
<%= content_for :title, "Blog Pages" %>

<h1>Blog Pages</h1>

<div class="pages">
  <% @pages.each do |page| %>
    <p>
      <%= link_to page.title, page %>
    </p>
  <% end %>
</div>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<%= render 'form', page: @page %>
<%= content_for :title, "New Page" %>

app/views/pages/show.html.erb
<%= content_for :title, @page.title %>
<h1><%= @page.title %></h1>
<p>
  <%= @page.body %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %>
<%= link_to 'Delete', :page, method: :delete, data: { confirm: 'are you sure?' } %>

<div style="margin-top: 15px">
  <%= link_to 'Back to All Pages', '/pages' %>
</div>

app/views/playground/_css_grid.html.erb
<div class="container">
  <div class="heading">
    <h2>CSS Grid</h2>
    <p>We define grid tracks using grid-template-columns and grid-template-rows.
      Both properties specify the size of the grid tracks.</p>
  </div>
  <div class="css-grid">
    <div class="item">1</div>
    <div class="item">2</div>
    <div class="item">3</div>
    <div class="item">4</div>
    <div class="item">5</div>
    <div class="item">6</div>
  </div>

  <div class="col-container">
    <div class="col">
      <h2>Column 1</h2>
      <p>Hello World</p>
    </div>
    <div class="col">
      <h2>Column 2</h2>
      <p>Hello World</p>
      <p>Hello World</p>
      <p>Hello World</p>
      <p>Hello World</p>
    </div>
    <div class="col">
      <h2>Column 3</h2>
      <p>Some other text..</p>
      <p>Some other text..</p>
    </div>
  </div>
</div>

app/views/playground/index.html.erb
<!--Ability to go back to the previous page-->

<!DOCTYPE html>
<html>
<head>
  <%= content_for :title, "Playground" %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
</head>
<body>

<div class="wrapper">


  <%= render 'css_grid' %>

  <div class="container">
    <div class="heading">
      <h2>AJAX</h2>
      <p>AJAX is a set of techniques used to dynamically display content and data.
        This is often referred to as asynchronous programming.
      </p>
    </div>
    <div class="names-section">
      <button class="names-button">Click Me</button>
      <h3 class="appear-text">Names will appear here</h3>
      <div class="name-div"></div>
      <%=link_to 'Edit names', names_path, class: 'edit-names' %>
    </div>
  </div>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="button-primary">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post_cards.html.erb
<div class="post-cards">
  <% Post.all.each do |post| %>
    <div class="card-grid">
      <div class="card-grid-item">
        <div class="card">
          <%= image_tag "desk.jpg", class: "card-image" %>
          <div class="card-content">
            <h1 class="card-title"><%= post.title %></h1>
            <p class="card-body"><%= post.body %></p>
            <%= link_to "Read More", post_path(post), class: "card-button"%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= content_for :title, "Edit #{@post.title} Post" %>
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back to all posts', posts_path %>

app/views/posts/index.html.erb
<%= content_for :title, "Blog Posts" %>

<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= content_for :title, "#{@post.title}" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back to all posts', posts_path %>

app/views/readme/index.html.erb
<h1>Readme#index</h1>
<p>Find me in app/views/readme/index.html.erb</p>

app/views/shared/_nav.html.erb
<!--Navigation-->
<nav class="top-nav">
  <%= link_to "Home", root_path, :class => current_class?(root_path) %>
  <%= active_link_to 'Posts', posts_path %>
  <%= active_link_to 'Readme', readme_path %>
  <div class="dropdown">
    <%= active_link_to 'Playground', playground_path %>
  </div>
</nav>

<!-- Dropdown for navigation -->
<!--<div class="dropdown">-->
<!--  <div class="dropbtn">Dropdown-->
<!--    <i class="ff fa-caret-down"></i>-->
<!--    <div class="dropdown-content">-->
<!--      <a href="#">Link 1</a>-->
<!--      <a href="#">Link 2</a>-->
<!--      <a href="#">Link 3</a>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->

app/views/welcome/index.html.erb
<%= content_for :title, "Welcome" %>

<div class="hero-image">
  <%= image_tag "forest.jpg", class: "forest-image" %>
  <h1 class="picture-heading-text">Welcome to the blog builder!</h1>
  <p class="picture-copy-text">Nov 1, 2020</p>
</div>

<div class="grid-container">
  <%= render 'posts/post_cards' %>
</div>